spring.application.name=backend
server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d7iilhm7r5hc73bivmq0-a/auramusic
spring.datasource.username=admin
spring.datasource.password=83R3k5XxWpsm2TVsrW7P38SI5HffpJuX
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aura.learn.ad@gmail.com
spring.mail.password=dnbomaijbgtyvaou
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true