spring.application.name=backend

# ===============================
# CONFIGURACION DE BASE DE DATOS
# ===============================
spring.datasource.url=jdbc:postgresql://dpg-d7iilhm7r5hc73bivmq0-a/auramusic
spring.datasource.username=admin
spring.datasource.password=83R3k5XxWpsm2TVsrW7P38SI5HffpJuX
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACION DE HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true